# Generated by Django 3.0.5 on 2020-07-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(default='87014a55cbf011ea9cb0f07959907aeb', max_length=200, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=600)),
                ('age', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('birthday', models.DateTimeField()),
                ('image', models.ImageField(default='authors/images/noimage.png', upload_to='authors/images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default='87012345cbf011ea9095f07959907aeb', max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=330)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
                ('bookImg', models.ImageField(default='books/images/noimage.png', upload_to='books/images/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('price', models.FloatField(default=0)),
                ('draft', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
