# Generated by Django 3.0.5 on 2020-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200722_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='363030d9cbf211ea8991f07959907aeb', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='363057eacbf211eaadd1f07959907aeb', max_length=200, primary_key=True, serialize=False),
        ),
    ]
