# Generated by Django 3.0.5 on 2020-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200723_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='about',
            new_name='biography',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='b2d5c97c98774e8f9e27be1b286f62ea', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='898bf4eac86b4f8d96aba41e8336acf7', max_length=200, primary_key=True, serialize=False),
        ),
    ]
