# Generated by Django 3.0.5 on 2020-07-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200723_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='3e38f963edb24b03857d3cb1e4e43686', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='49e2cb3f7a664ea5932ff980cc7296d2', max_length=200, primary_key=True, serialize=False),
        ),
    ]
