# Generated by Django 3.0.5 on 2020-07-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200723_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='14cbf4c9a2934d05b8c5a5ffb678c5c5', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='d650393e1e65430f9e727d8ca19e8ce6', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
